"use client";
import { useState, useRef, useEffect } from "react";
import Link from "next/link";
import { motion, AnimatePresence } from "framer-motion";
import {
  IconSend, IconRobot, IconUser,
  IconDownload, IconArrowLeft,
  IconAlertTriangle
} from "@tabler/icons-react";

type Message = {
  id: string;
  role: "user" | "assistant";
  content: string;
  timestamp: Date;
};

export default function ChatPage() {
  const [messages, setMessages] = useState<Message[]>([
    {
      id: "1",
      role: "assistant",
      content: "👋 Hello! I'm MyCare+ AI, your personal medical assistant.\n\nI'm here to help you understand your symptoms and guide you toward the right care.\n\nPlease note: I provide information and suggestions only — not a medical diagnosis. Always consult a real doctor for serious concerns.\n\n**What is your main symptom or health concern today?**",
      timestamp: new Date()
    }
  ]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [sessionNotes, setSessionNotes] = useState<string[]>([]);
  const bottomRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  const sendMessage = async () => {
    if (!input.trim() || loading) return;

    const userMessage: Message = {
      id: Date.now().toString(),
      role: "user",
      content: input.trim(),
      timestamp: new Date()
    };

    setMessages(prev => [...prev, userMessage]);
    setSessionNotes(prev => [...prev, input.trim()]);
    setInput("");
    setLoading(true);

    try {
      const response = await fetch("/api/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          messages: [...messages, userMessage].map(m => ({
            role: m.role,
            content: m.content
          }))
        })
      });

      const data = await response.json();

      const assistantMessage: Message = {
        id: (Date.now() + 1).toString(),
        role: "assistant",
        content: data.message || "I apologize, I couldn't process that. Please try again.",
        timestamp: new Date()
      };

      setMessages(prev => [...prev, assistantMessage]);
    } catch (error) {
      const errorMessage: Message = {
        id: (Date.now() + 1).toString(),
        role: "assistant",
        content: "⚠️ Something went wrong. Please check your connection and try again.",
        timestamp: new Date()
      };
      setMessages(prev => [...prev, errorMessage]);
    } finally {
      setLoading(false);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      sendMessage();
    }
  };

  const downloadReport = () => {
    const report = `
MYCARE+ CONSULTATION REPORT
============================
Date: ${new Date().toLocaleDateString()}
Time: ${new Date().toLocaleTimeString()}

CONVERSATION TRANSCRIPT:
------------------------
${messages.map(m =>
  `[${m.role.toUpperCase()}] ${m.content}`
).join("\n\n")}

============================
DISCLAIMER: This report is generated by AI and is for informational purposes only.
Please consult a qualified medical professional for proper diagnosis and treatment.
    `;

    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `MyCare-Report-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const formatMessage = (content: string) => {
    return content
      .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
      .replace(/\*(.*?)\*/g, "<em>$1</em>")
      .replace(/\n/g, "<br/>");
  };

  return (
    <main style={{
      height: "100vh",
      background: "#0B0F0C",
      display: "flex",
      flexDirection: "column",
      position: "relative",
      overflow: "hidden"
    }}>

      {/* Grid Background */}
      <div style={{
        position: "fixed", inset: 0,
        backgroundImage: "linear-gradient(rgba(0,230,118,0.02) 1px, transparent 1px), linear-gradient(90deg, rgba(0,230,118,0.02) 1px, transparent 1px)",
        backgroundSize: "60px 60px",
        pointerEvents: "none"
      }}/>

      {/* ── HEADER ── */}
      <div style={{
        padding: "16px 24px",
        background: "rgba(11,15,12,0.9)",
        backdropFilter: "blur(20px)",
        borderBottom: "1px solid rgba(255,255,255,0.05)",
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        zIndex: 10
      }}>
        <div style={{ display: "flex", alignItems: "center", gap: 14 }}>
          <Link href="/dashboard" style={{
            width: 34, height: 34, borderRadius: 9,
            background: "rgba(255,255,255,0.04)",
            border: "1px solid rgba(255,255,255,0.07)",
            display: "flex", alignItems: "center",
            justifyContent: "center", textDecoration: "none"
          }}>
            <IconArrowLeft size={15} color="#4a6a4a"/>
          </Link>

          <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <div style={{
              width: 36, height: 36, borderRadius: 10,
              background: "linear-gradient(135deg, rgba(0,230,118,0.15), rgba(0,188,212,0.08))",
              border: "1px solid rgba(0,230,118,0.2)",
              display: "flex", alignItems: "center", justifyContent: "center"
            }}>
              <IconRobot size={18} color="#00E676"/>
            </div>
            <div>
              <p style={{ fontSize: 14, fontWeight: 700, color: "#E8F5E9", margin: 0 }}>
                MyCare+ AI
              </p>
              <p style={{ fontSize: 11, color: "#00E676", margin: 0, display: "flex", alignItems: "center", gap: 4 }}>
                <span style={{
                  width: 6, height: 6, borderRadius: "50%",
                  background: "#00E676", display: "inline-block",
                  animation: "pulse 2s infinite"
                }}/>
                Online — Medical Assistant
              </p>
            </div>
          </div>
        </div>

        <div style={{ display: "flex", gap: 8 }}>
          <button
            onClick={downloadReport}
            style={{
              display: "flex", alignItems: "center", gap: 6,
              padding: "8px 14px", borderRadius: 9,
              background: "rgba(255,255,255,0.03)",
              border: "1px solid rgba(255,255,255,0.07)",
              color: "#7A8F85", fontSize: 12,
              fontWeight: 600, cursor: "pointer",
              fontFamily: "inherit"
            }}>
            <IconDownload size={14}/>
            Download Report
          </button>
        </div>
      </div>

      {/* ── DISCLAIMER ── */}
      <div style={{
        padding: "10px 24px",
        background: "rgba(255,180,0,0.04)",
        borderBottom: "1px solid rgba(255,180,0,0.08)",
        display: "flex", alignItems: "center", gap: 8
      }}>
        <IconAlertTriangle size={13} color="#f59e0b"/>
        <p style={{ fontSize: 11, color: "#92714a", margin: 0 }}>
          MyCare+ AI provides informational guidance only — not a substitute for professional medical advice. For emergencies call <strong style={{ color: "#f59e0b" }}>112</strong>
        </p>
      </div>

      {/* ── MESSAGES ── */}
      <div style={{
        flex: 1,
        overflowY: "auto",
        padding: "24px",
        display: "flex",
        flexDirection: "column",
        gap: 16,
        maxWidth: 800,
        width: "100%",
        margin: "0 auto"
      }}>
        <AnimatePresence>
          {messages.map((message) => (
            <motion.div
              key={message.id}
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.35 }}
              style={{
                display: "flex",
                gap: 12,
                flexDirection: message.role === "user" ? "row-reverse" : "row",
                alignItems: "flex-start"
              }}>

              {/* Avatar */}
              <div style={{
                width: 34, height: 34,
                borderRadius: 10, flexShrink: 0,
                background: message.role === "user"
                  ? "linear-gradient(135deg, #00E676, #00C853)"
                  : "linear-gradient(135deg, rgba(0,230,118,0.15), rgba(0,188,212,0.08))",
                border: message.role === "assistant"
                  ? "1px solid rgba(0,230,118,0.2)" : "none",
                display: "flex", alignItems: "center", justifyContent: "center"
              }}>
                {message.role === "user"
                  ? <IconUser size={16} color="#000"/>
                  : <IconRobot size={16} color="#00E676"/>
                }
              </div>

              {/* Bubble */}
              <div style={{
                maxWidth: "75%",
                padding: "14px 18px",
                borderRadius: message.role === "user"
                  ? "18px 4px 18px 18px"
                  : "4px 18px 18px 18px",
                background: message.role === "user"
                  ? "linear-gradient(135deg, #00E676, #00C853)"
                  : "rgba(255,255,255,0.04)",
                border: message.role === "assistant"
                  ? "1px solid rgba(255,255,255,0.07)" : "none",
                color: message.role === "user" ? "#000" : "#E8F5E9",
                fontSize: 14,
                lineHeight: 1.7,
                fontWeight: message.role === "user" ? 600 : 400
              }}>
                <div dangerouslySetInnerHTML={{
                  __html: formatMessage(message.content)
                }}/>
                <p style={{
                  fontSize: 10, margin: "8px 0 0",
                  opacity: 0.5,
                  color: message.role === "user" ? "#000" : "#7A8F85"
                }}>
                  {message.timestamp.toLocaleTimeString([], {
                    hour: "2-digit", minute: "2-digit"
                  })}
                </p>
              </div>

            </motion.div>
          ))}
        </AnimatePresence>

        {/* Loading */}
        {loading && (
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            style={{ display: "flex", gap: 12, alignItems: "flex-start" }}>
            <div style={{
              width: 34, height: 34, borderRadius: 10,
              background: "linear-gradient(135deg, rgba(0,230,118,0.15), rgba(0,188,212,0.08))",
              border: "1px solid rgba(0,230,118,0.2)",
              display: "flex", alignItems: "center", justifyContent: "center"
            }}>
              <IconRobot size={16} color="#00E676"/>
            </div>
            <div style={{
              padding: "14px 18px",
              background: "rgba(255,255,255,0.04)",
              border: "1px solid rgba(255,255,255,0.07)",
              borderRadius: "4px 18px 18px 18px",
              display: "flex", gap: 6, alignItems: "center"
            }}>
              {[0, 1, 2].map(i => (
                <div key={i} style={{
                  width: 7, height: 7, borderRadius: "50%",
                  background: "#00E676",
                  animation: `bounce 1.2s infinite ${i * 0.2}s`
                }}/>
              ))}
            </div>
          </motion.div>
        )}

        <div ref={bottomRef}/>
      </div>

      {/* ── INPUT ── */}
      <div style={{
        padding: "16px 24px 24px",
        background: "rgba(11,15,12,0.9)",
        backdropFilter: "blur(20px)",
        borderTop: "1px solid rgba(255,255,255,0.05)"
      }}>
        <div style={{
          maxWidth: 800, margin: "0 auto",
          display: "flex", gap: 10, alignItems: "flex-end"
        }}>
          <div style={{ flex: 1, position: "relative" }}>
            <textarea
              ref={inputRef}
              value={input}
              onChange={e => setInput(e.target.value)}
              onKeyDown={handleKeyDown}
              placeholder="Describe your symptoms... (Press Enter to send)"
              rows={1}
              style={{
                width: "100%",
                padding: "14px 18px",
                background: "rgba(255,255,255,0.04)",
                border: "1px solid rgba(255,255,255,0.08)",
                borderRadius: 14,
                color: "#E8F5E9",
                fontSize: 14,
                outline: "none",
                resize: "none",
                fontFamily: "inherit",
                lineHeight: 1.6,
                transition: "all 0.3s ease",
                maxHeight: 120,
                overflowY: "auto"
              }}
              onFocus={e => {
                e.target.style.borderColor = "rgba(0,230,118,0.4)";
                e.target.style.background = "rgba(0,230,118,0.03)";
              }}
              onBlur={e => {
                e.target.style.borderColor = "rgba(255,255,255,0.08)";
                e.target.style.background = "rgba(255,255,255,0.04)";
              }}
            />
          </div>

          <button
            onClick={sendMessage}
            disabled={!input.trim() || loading}
            style={{
              width: 48, height: 48,
              borderRadius: 13,
              background: input.trim() && !loading
                ? "linear-gradient(135deg, #00E676, #00C853)"
                : "rgba(255,255,255,0.04)",
              border: "none",
              cursor: input.trim() && !loading ? "pointer" : "not-allowed",
              display: "flex", alignItems: "center",
              justifyContent: "center",
              transition: "all 0.3s ease",
              flexShrink: 0,
              boxShadow: input.trim() && !loading
                ? "0 4px 16px rgba(0,230,118,0.25)" : "none"
            }}>
            <IconSend size={18} color={input.trim() && !loading ? "#000" : "#2a4a2a"}/>
          </button>
        </div>

        <p style={{
          fontSize: 11, color: "#2a4a2a",
          textAlign: "center", marginTop: 10
        }}>
          Press Enter to send • Shift+Enter for new line
        </p>
      </div>

      <style>{`
        @keyframes bounce {
          0%, 60%, 100% { transform: translateY(0); }
          30% { transform: translateY(-8px); }
        }
        @keyframes pulse {
          0%, 100% { opacity: 1; }
          50% { opacity: 0.4; }
        }
      `}</style>

    </main>
  );
}